name = "avrg-dev"
main = "src/index.ts"
compatibility_date = "2022-09-30"

kv_namespaces = [
  { binding = "URLS", id = "", preview_id = "" }
]

[vars]
B2URL = ""
B2BUCKET = ""
B2_KEY_ID = ""
B2_BUCKET_ID = ""
PATH_PREFIX = ""
REDIRECT_URL = ""